### ISSUE TITLE
Task description

### ISSUE THREAD

**Issue by rafaelrinaldi** [ruyadorno/ntl#17]
It would be very handy if `ntl` provided a way to display a description about the available tasks. I believe it would be failry straightforward to implement this.

If you think it's a good idea I can give it a shot.

**Comment by ruyadorno** [comment]
hey @rafaelrinaldi thanks for stopping by!

by task descriptions do you mean like we discussed in #4 ?

**Comment by rafaelrinaldi** [comment]
That looks like it! I offer myself to tackle it if there is interest.

**Comment by ruyadorno** [comment]
oh yeah 🎉 sure thing! that'd be awesome!

in the end of that discussion I think the [bash comment](https://github.com/npm/npm/issues/15154#issuecomment-275791993) idea was the best way to go about it we could come up with, do you agree?

anyways, any help is super appreciated!

many thanks!

**Comment by ruyadorno** [comment]
@rafaelrinaldi heads up, major refactor just landed on master 😊

**Comment by ruyadorno** [comment]
I'll close this one since it's def a duplicate of #4 

let's follow up with the discussion there! many thanks!
