### ISSUE TITLE
Misleading error message when package.json is malformed

### ISSUE THREAD

**Issue by Calinou** [ruyadorno/ntl#29]
**Node.js version:** 8.12.0
**ntl version:** 3.0.0

Attempting to run ntl with a malformed `package.json` (with a missing comma, for instance) will display the following error message:

```
✖  No package.json found
```

The error message should be different when `package.json` is malformed to make troubleshooting easier.

**Comment by mischah** [comment]
I’m currently working on this.

**Comment by mischah** [comment]
PR is created :octocat:
