### ISSUE TITLE
Descriptions abruptly stopped displaying

### ISSUE THREAD

**Issue by bassplayer7** [ruyadorno/ntl#34]
I have been using `ntl` for a while but today, it abruptly stopped working. Is there anything in particular that may have caused this? I am not aware of a change in my environment.

Here's a reduced example of my `package.json`:

```
{
  "scripts": {
    "dev": "ntl -d -o",
    "dev:app": "cd ui/app && yarn serve",
    "dev:config": "cd ui/config && yarn serve"
  },
  "ntl": {
    "descriptions": {
      "dev:app": "Run app",
      "dev:config": "Run Config"
    }
  }
}
```

Output:

> $ yarn dev
> yarn run v1.13.0
> $ ntl -d -o
> No descriptions for your npm scripts found
> ✔  Npm Task List - v3.1.0
> ? Select a task to run: (Use arrow keys)
>

**Comment by mischah** [comment]
Which Node.js Version are you using?

**Comment by bassplayer7** [comment]
Node v11.9.0

**Comment by mischah** [comment]
Oops. It was a bug I brought in with #33. 

Sorry 🙈

A already created a PR to fix this. Hope @ruyadorno will publish this soonish.

**Comment by ruyadorno** [comment]
done ✅ 

thanks for the quick fix @mischah 😄

**Comment by mischah** [comment]
No problem 😅

**Comment by bassplayer7** [comment]
Wow! Thanks for the quick effort, friends. I can confirm it is working once again.

**Comment by duckscofield** [comment]
I have the same problem. I use node v12.13.0 version
