### ISSUE TITLE
Description + Exclude

### ISSUE THREAD

**Issue by egor-xyz** [ruyadorno/ntl#41]
`ntl -d -e start`
Didn't exlude start script from menu

**Comment by mischah** [comment]
Confirmed. I’m able to reproduce this with ntl `v3.2.3`.

Seems to be a bug. 

@ruyadorno Can you assign this one to me?

**Comment by ruyadorno** [comment]
sure thing 👍

**Comment by ruyadorno** [comment]
thanks for the prompt fix @mischah 😄

**Comment by ruyadorno** [comment]
and @egor-xyz for the prompt report! 🎉
