### ISSUE TITLE
An option for choosing custom npm client

### ISSUE THREAD

**Issue by oMaten** [ruyadorno/ntl#43]
For now, `ntl` use npm to execute script by default. I need to use private npm client to execute script for some reasons(like preset npm remote registry, etc...), so is it possible to add an option for setting private npm client?

**Comment by ruyadorno** [comment]
that's something I had in the back of my mind for a while but never really had the time to work on it - I think it's definitely very nice to have 👍

**Comment by Calinou** [comment]
I suppose this would also be useful to run scripts using Yarn instead of npm, which can be slightly faster in my experience.

**Comment by ruyadorno** [comment]
Landed in #49
