### ISSUE TITLE
Conflict with Netlify `ntl` command

### ISSUE THREAD

**Issue by wgolledge** [ruyadorno/ntl#46]
Netlfiy have recently added a shorthand `ntl` command that interferes with this command when both are installed on the same machine (this happens with or without `npx`).

Would it be possible to rename this command, or also have it listed under another (longhand?) command so that users are still able to access it after using Netlify.

Edit: I'm able to run with `npx -p ntl --no-install ntl` but it's a bit contrived.

**Comment by ruyadorno** [comment]
@wgolledge thanks for the heads up! I'll bring it up to the https://github.com/netlify/cli repo team first and see if maybe they want to avoid the conflict from their side but anyways I think a longhand command might be a good idea (given that **ntl** are just three letters and so easy to have conflicting acronyms)

**Comment by ruyadorno** [comment]
if anyone wants to send a PR adding a longhand option, that's def welcomed, I don't feel particularly inspired right now but I guess `npm-tasklist` or `npmtl` could do the trick

PS: just make sure it doesn't conflict with yet another CLI 😂

**Comment by wgolledge** [comment]
I'll get on it 😄 

`npm-tasklist` sounds like a good longhand option to me
