### ISSUE TITLE
Requesting escape key and visual end marker.

### ISSUE THREAD

**Issue by uipoet** [ruyadorno/ntl#6]
`ntl` is very useful. Thank you!

Really appreciate that `j` and `k` are mapped so I can cruise tasks vim-style.

In addition, it would be great to have `esc` to exit `ntl` and to add a visual separator between the last choice and when it revolves back around to the beginning.

**Comment by ruyadorno** [comment]
all good sugestions, thanks @uipoet 

- `esc` to exit makes a lot of sense :+1: would merge a PR :blush: 
- visual mark, I'm not so sure about it :-1: 
  - I don't think there's a native way to implement a separator using the current [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) API
  - we could work around it, just by appending an non-interactive item at the end of choices but I'm not sure that will be a great UX, not to say that many people will not even see the "looping" feature most of the time (projects with only 2 or 3 npm scripts)
  - I honestly don't see that much value on having it (?) we could use some more feedback here

**Comment by uipoet** [comment]
I'll take a stab at a PR for `esc` this weekend.

I see looping on all my projects (several scripts on each). Took me a little while to realize what was happening. Even with the knowledge, I still find it awkward to know if I have been to the end of the list. No solution, given the constraints you mentioned, is apparent to me at this time.

**Comment by yaroslavya** [comment]
Also think `esc` or some other key to cancel tasks listing would be helpful. :+1:

**Comment by ruyadorno** [comment]
landed on `1.2.0`

thanks @darahak for adding it in #10
