### ISSUE TITLE
[BUG] Not an internal or external command, executable program or batch file

### ISSUE THREAD

**Issue by w3bsme** [ruyadorno/ntl#62]
![help pls](https://user-images.githubusercontent.com/29128703/86216937-6ce2bf80-bb87-11ea-9c2b-9e8592844c9b.png)

**Comment by ruyadorno** [comment]
Sounds like it could possibly be a npm setup issue, could you try `npm install -g` with different packages that provide a cli and confirm if those work? Examples:
- `npm install -g yo` - Should be able to run `yo --help` 
- `npm install -g diff-so-fancy` - Should be able to run `diff-so-fancy --help`

**Comment by w3bsme** [comment]
Solved :heart:
