### ISSUE TITLE
Feature Request: allow flags to be passed through to the npm script

### ISSUE THREAD

**Issue by fiznool** [ruyadorno/ntl#9]
Oftentimes I like to run scripts with the `--silent` flag to suppress the npm output when an error occurs, e.g. `npm run specs --silent`.

It would be nice if we could somehow pass through these flags from ntl.

**Comment by mischah** [comment]
@ruyadorno 

Should this be done by allowing something like:

```
ntl --descriptions -- --silent
```

This is the concept how one can pass options to commands used in npm scripts like described [here](https://michael-kuehnel.de/tooling/2018/03/22/helpers-and-tips-for-npm-run-scripts.html#passing-options-to-used-commands).

**Comment by ruyadorno** [comment]
yep 👍ideally yes
